### ISSUE TITLE
Kalite Seçimi

### ISSUE THREAD

**Issue by Prohibitive** [gorkembayraktar/dizibox-tool#1]
Merhabalar Mükemmel bir tools yapmışsınız emeklerinize sağlık.
Deneme Şansım oldu lakin kalite seçiminde kaliteler listelenmiyor. Acaba güncelleme gibi bir imkanınız var mı?
Saygılarımla.

**Comment by gorkembayraktar** [comment]
merhaba, sorun düzeltildi.

**Comment by Prohibitive** [comment]
Aman allahım ağlamak istiyorum bu kadar hızlı cevap vermenizi beklemiyordum. hemen deneyeceğim.
