### ISSUE TITLE
Çözünürlük Bulunamadı

### ISSUE THREAD

**Issue by Prohibitive** [gorkembayraktar/dizibox-tool#3]
![image](https://github.com/gorkembayraktar/dizibox-tool/assets/22181509/64c92a62-ff41-4682-bf87-2e2f90bacfa2)
Merhabalar. Çözünürlük Seçiminden Kaynaklı sanırım.

**Comment by gorkembayraktar** [comment]
Güncelleme;
Çözünürlük bulunmuyorsa, varsayılan çözünürlük aranıyor. Varsayılan çözünürlükte yoksa onay işlemi istiyor.
