### ISSUE TITLE
dizibox.in

### ISSUE THREAD

**Issue by Prohibitive** [gorkembayraktar/dizibox-tool#6]
Merhabalar domain değiştirmişler sanırım bu yüzden çalışmıyor.
Saygılarımla

**Comment by gorkembayraktar** [comment]
Merhaba, 
İlgili adresi güncelledim, eğer domain tekrar değişirse .env dosyasında güncel domaini tanımlayabilirsiniz.

**Comment by Prohibitive** [comment]
Emeklerinize sağlık hocam.
Çok teşekkür ederim.
